[project]
name = "steam-metrics-cibertec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastavro>=1.12.2",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pandera>=0.32.1",
    "plotly>=6.9.0",
    "psutil>=7.2.2",
    "pyarrow>=25.0.0",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "streamlit>=1.59.1",
]

[tool.pyright]
extraPaths = ["."]
